---
title: ""
---

## Publications

- **Bassukas, D.**; Emmanouilidis, A.; Avramidis, P. Late Holocene Hydro-Climatic Variability in the Eastern Mediterranean: A Spatial Multiproxy Approach. Water **2021**, 13, 3252. https://doi.org/10.3390/w13223252

- Emmanouilidis, A.; Messaris, G.; Ntzanis, E.; Zampakis, P.; Prevedouros, I.; **Bassukas, D. A.**; Avramidis, P. CT Scanning, X-Ray Fluorescence: Non-Destructive Techniques for the Identification of Sedimentary Facies and Structures. Revue de Micropaleontologie **2020**, 67, 100410. https://doi.org/10.1016/j.revmic.2020.100410.    

## Other
### Conference Papers

- **Bassukas, D.**; Emmanouilidis, A.; Panagiotaras, D.; Avramidis, P. Sedimentological and geochemical evaluation of Vouliagmeni lake sediments, Perachora peninsula, Corinth, Greece. 19th International Multidisciplinary Scientific GeoConference SGEM 2019, **2019**, 19, 505–512. https://doi.org/10.5593/sgem2019/1.1/S01.062.

### Presentations

- Külls, C. and **Bassukas, D.**: Groundwater salinization dynamics - a conceptual modeling approach to prioritize water management plans in a changing environment, EGU General Assembly 2022, Vienna, Austria, 23–27 May 2022, EGU22-12667, https://doi.org/10.5194/egusphere-egu22-12667, **2022**.

- **Bassukas, D.**; Emmanouilidis, A.; Panagiotaras, D.; Avramidis, P. Spatial Sedimentological, Geochemical and Mineralogical Characterization of Vouliagmeni Coastal Lake, Greece, **2019**. 15th International Congress of the Geological Society of Greece, Harokopio University of Athens.


